spring:
  datasource:
    url: jdbc:mysql://localhost/testdb?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
      time-between-eviction-runs-millis: 7200000
  jpa:
    show-sql: false
    properties:
      hibernate:
        query:
          plan_cache_max_size: 32
          plan_parameter_metadata_max_size: 64
  quartz:
    scheduler-name: QuartzScheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      autoStartup: false
      org.quartz.threadPool.threadCount: 5
  batch:
    job.enabled: false